server:
  port: 7500
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/ # this is the eureka server address
  instance:
    appname: paymentservice
spring:
  activemq:
    broker-url: tcp://localhost:61616
  datasource:
    url: jdbc:mysql://localhost:3306/ordermgmtdb
    username: root
    password: secret
    driverClassName: com.mysql.jdbc.Driver
    maximum-pool-size: 30
  cloud:
    application:
      name: paymentservice